### ISSUE TITLE
clone_error_16_17_50.txt

### ISSUE THREAD

**Issue by Mikewins1** [sud0nick/PortalAuth#27]
I am getting this error after trying to clone a site.  clone_error_16_17_50.txt

clone_error_16_17_50.txt

Traceback (most recent call last): File "/pineapple/modules/PortalAuth/includes/scripts/portalclone.py", line 4, in from PortalCloner import PortalCloner File "/sd/modules/PortalAuth/includes/scripts/PortalCloner.py", line 12, in import requests File "/sd/modules/PortalAuth/includes/scripts/libs/requests/__init__.py", line 53, in from .packages.urllib3.contrib import pyopenssl File "/sd/modules/PortalAuth/includes/scripts/libs/requests/packages/__init__.py", line 63, in load_module __import__(name) File "/sd/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/__init__.py", line 10, in from .connectionpool import ( File "/sd/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/connectionpool.py", line 37, in from .request import RequestMethods File "/sd/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/request.py", line 6, in from .filepost import encode_multipart_formdata File "/sd/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/filepost.py", line 10, in writer = codecs.lookup('utf-8')[3] LookupError: unknown encoding: utf-8

**Comment by https-sam** [comment]
Same. Do you have any solution for this?

**Comment by sud0nick** [comment]
You need to run `opkg install python-codecs` on your Pineapple.  If you download the module from GitHub instead of the module manager it will get installed automatically.
