### ISSUE TITLE
Error thrown during cloning process

### ISSUE THREAD

**Issue by etkCan** [sud0nick/PortalAuth#29]
PortalAuth version 1.9 on Wifi Pineapple Tetra

Error is listed below. I am unable to clone any sites and I have tried a variety with different settings.

Traceback (most recent call last): File "/pineapple/modules/PortalAuth/includes/scripts/portalclone.py", line 4, in from PortalCloner import PortalCloner File "/pineapple/modules/PortalAuth/includes/scripts/PortalCloner.py", line 12, in import requests File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/__init__.py", line 53, in from .packages.urllib3.contrib import pyopenssl File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/packages/__init__.py", line 63, in load_module __import__(name) File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/__init__.py", line 10, in from .connectionpool import ( File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/connectionpool.py", line 37, in from .request import RequestMethods File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/request.py", line 6, in from .filepost import encode_multipart_formdata File "/pineapple/modules/PortalAuth/includes/scripts/libs/requests/packages/urllib3/filepost.py", line 10, in writer = codecs.lookup('utf-8')[3] LookupError: unknown encoding: utf-8

**Comment by turmsegler** [comment]
On the current Pineapple firmware you need to install python-codecs as an additional dependency.

**Comment by sud0nick** [comment]
@turmsegler is correct.  Please run `opkg install python-codecs`.
